
#---------------Redis Database Configurations------------------------------------------
#redis:
#  host: ${REDIS_HOST:112.196.108.244}
#  port: ${REDIS_PORT:6379}
#  eventSourceDatabase: ${REDIS_EVENT_SOURCING_DATABASE_NUMBER:0}
#  cacheDatabase: ${REDIS_CACHE_DATABASE_NUMBER:3}
#  password: ${REDIS_PASSWORD:CHuJukJQCrr23kLs}
#  cluster-nodes: ${REDIS_CLUSTER_NODES:}
#  max-retries: ${REDIS_MAX_RETRY:}
#  cache:
#    default:
#      duration: ${REDIS_DEFAULT_CACHE_DURATION_IN_MINUTES:600}
#    list:


#redis:
#  host: 112.196.108.244
#  port: 6379
#  database: 0
#  timeout: 60
#  password: CHuJukJQCrr23kLs
#  cache:
#    default:
#      duration: 2400
#    list:
#      -
#        name: searchTextCache
#        duration: 600

redis:
  host: localhost
  port: 6379
  database: 0
  timeout: 60
  password:
  cache:
    default:
      duration: 2400
    list:
      -
        name: productService
        duration: 600

